/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.view;

import com.java.controller.DashboardController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Madushan Lahiru
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setIconImage(new ImageIcon("images/logo_1.png").getImage());
        
        btn_statistics.setVisible(false);
        btn_editRecords.setVisible(false);
        btn_editCourierDetails.setVisible(false);
        btn_reports.setVisible(false);

        DashboardController controller = new DashboardController();
        try {
            String[] users = controller.getPageAccessUsers();
            for(String user : users) {
                if (user != null && user.equals(System.getProperty("user.name"))) {
                    btn_statistics.setVisible(true);
                    btn_editRecords.setVisible(true);
                    btn_editCourierDetails.setVisible(true);
                    btn_reports.setVisible(true);
                }
            }
            
            controller.closeDBConnetion();
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_statistics = new javax.swing.JButton();
        btn_newEntry = new javax.swing.JButton();
        btn_updateEntry = new javax.swing.JButton();
        btn_history = new javax.swing.JButton();
        btn_URUpdate = new javax.swing.JButton();
        btn_addCourierSchedule = new javax.swing.JButton();
        btn_printCourierSchedule = new javax.swing.JButton();
        btn_reports = new javax.swing.JButton();
        btn_editRecords = new javax.swing.JButton();
        btn_editCourierDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment System");
        setIconImages(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Payments System");

        jLabel3.setText("Vallibel Finance PLC");

        jLabel4.setText("Version 2.6.0");

        jLabel5.setText("© The MIT License 2021");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        btn_statistics.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_statistics.setText("Statistics");
        btn_statistics.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_statistics.setMaximumSize(new java.awt.Dimension(225, 45));
        btn_statistics.setMinimumSize(new java.awt.Dimension(150, 35));
        btn_statistics.setPreferredSize(new java.awt.Dimension(300, 45));
        btn_statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_statisticsActionPerformed(evt);
            }
        });
        jPanel2.add(btn_statistics);

        btn_newEntry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_newEntry.setText("Accepting New Files");
        btn_newEntry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_newEntry.setMaximumSize(new java.awt.Dimension(225, 45));
        btn_newEntry.setMinimumSize(new java.awt.Dimension(150, 35));
        btn_newEntry.setPreferredSize(new java.awt.Dimension(300, 45));
        btn_newEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newEntryActionPerformed(evt);
            }
        });
        jPanel2.add(btn_newEntry);

        btn_updateEntry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_updateEntry.setText("Update Process / Return Received");
        btn_updateEntry.setToolTipText("");
        btn_updateEntry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_updateEntry.setMaximumSize(new java.awt.Dimension(225, 45));
        btn_updateEntry.setMinimumSize(new java.awt.Dimension(150, 35));
        btn_updateEntry.setPreferredSize(new java.awt.Dimension(300, 45));
        btn_updateEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateEntryActionPerformed(evt);
            }
        });
        jPanel2.add(btn_updateEntry);

        btn_history.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_history.setText("All Recorded Files");
        btn_history.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_history.setMaximumSize(new java.awt.Dimension(225, 45));
        btn_history.setMinimumSize(new java.awt.Dimension(150, 35));
        btn_history.setPreferredSize(new java.awt.Dimension(300, 45));
        btn_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historyActionPerformed(evt);
            }
        });
        jPanel2.add(btn_history);

        btn_URUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_URUpdate.setText("U/R Vehicle No Update");
        btn_URUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_URUpdate.setMaximumSize(new java.awt.Dimension(225, 45));
        btn_URUpdate.setMinimumSize(new java.awt.Dimension(150, 35));
        btn_URUpdate.setPreferredSize(new java.awt.Dimension(300, 45));
        btn_URUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_URUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_URUpdate);

        btn_addCourierSchedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_addCourierSchedule.setText("Add Cheque Records");
        btn_addCourierSchedule.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_addCourierSchedule.setMaximumSize(new java.awt.Dimension(225, 45));
        btn_addCourierSchedule.setMinimumSize(new java.awt.Dimension(150, 35));
        btn_addCourierSchedule.setPreferredSize(new java.awt.Dimension(300, 45));
        btn_addCourierSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addCourierScheduleActionPerformed(evt);
            }
        });
        jPanel2.add(btn_addCourierSchedule);

        btn_printCourierSchedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_printCourierSchedule.setText("Print Courier Schedule");
        btn_printCourierSchedule.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_printCourierSchedule.setMaximumSize(new java.awt.Dimension(225, 45));
        btn_printCourierSchedule.setMinimumSize(new java.awt.Dimension(150, 35));
        btn_printCourierSchedule.setPreferredSize(new java.awt.Dimension(300, 45));
        btn_printCourierSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printCourierScheduleActionPerformed(evt);
            }
        });
        jPanel2.add(btn_printCourierSchedule);

        btn_reports.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_reports.setText("Generate Reports");
        btn_reports.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_reports.setMaximumSize(new java.awt.Dimension(225, 45));
        btn_reports.setMinimumSize(new java.awt.Dimension(150, 35));
        btn_reports.setPreferredSize(new java.awt.Dimension(300, 45));
        btn_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportsActionPerformed(evt);
            }
        });
        jPanel2.add(btn_reports);

        btn_editRecords.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editRecords.setText("Edit Records");
        btn_editRecords.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_editRecords.setMaximumSize(new java.awt.Dimension(225, 45));
        btn_editRecords.setMinimumSize(new java.awt.Dimension(150, 35));
        btn_editRecords.setPreferredSize(new java.awt.Dimension(300, 45));
        btn_editRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editRecordsActionPerformed(evt);
            }
        });
        jPanel2.add(btn_editRecords);

        btn_editCourierDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_editCourierDetails.setText("Edit Courier Details");
        btn_editCourierDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_editCourierDetails.setMaximumSize(new java.awt.Dimension(225, 45));
        btn_editCourierDetails.setMinimumSize(new java.awt.Dimension(150, 35));
        btn_editCourierDetails.setPreferredSize(new java.awt.Dimension(300, 45));
        btn_editCourierDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editCourierDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btn_editCourierDetails);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel1)
                .addGap(193, 193, 193))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editRecordsActionPerformed
        Edit editRecords = new Edit();
        editRecords.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editRecordsActionPerformed

    private void btn_statisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_statisticsActionPerformed
        Statistics statistics = new Statistics();
        statistics.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_statisticsActionPerformed

    private void btn_URUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_URUpdateActionPerformed
        URVehicleNoUpdate ur = new URVehicleNoUpdate();
        ur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_URUpdateActionPerformed

    private void btn_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportsActionPerformed
        Report report = new Report();
        report.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_reportsActionPerformed

    private void btn_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historyActionPerformed
        History history = new History();
        history.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_historyActionPerformed

    private void btn_updateEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateEntryActionPerformed
        UpdateEntry update = new UpdateEntry();
        update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_updateEntryActionPerformed

    private void btn_newEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newEntryActionPerformed
        NewEntry entry = new NewEntry();
        entry.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_newEntryActionPerformed

    private void btn_addCourierScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addCourierScheduleActionPerformed
        AddCourierSchedule schedule = new AddCourierSchedule();
        schedule.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_addCourierScheduleActionPerformed

    private void btn_printCourierScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printCourierScheduleActionPerformed
        PrintCourierSchedule printSchedule = new PrintCourierSchedule();
        printSchedule.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_printCourierScheduleActionPerformed

    private void btn_editCourierDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editCourierDetailsActionPerformed
        EditCourierSchedule editSchedule = new EditCourierSchedule();
        editSchedule.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_editCourierDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_URUpdate;
    private javax.swing.JButton btn_addCourierSchedule;
    private javax.swing.JButton btn_editCourierDetails;
    private javax.swing.JButton btn_editRecords;
    private javax.swing.JButton btn_history;
    private javax.swing.JButton btn_newEntry;
    private javax.swing.JButton btn_printCourierSchedule;
    private javax.swing.JButton btn_reports;
    private javax.swing.JButton btn_statistics;
    private javax.swing.JButton btn_updateEntry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
