/*
 * The MIT License
 *
 * Copyright 2021 Protector.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.java.view;

import com.java.CommonUtils;
import com.java.controller.EditController;
import com.java.entity.FileEntity;
import com.java.entity.FileReturnHistory;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Protector
 */
public class Edit extends javax.swing.JFrame {

    private EditController editController;
    private SimpleDateFormat dateFormat;
    
    private List<Object> changedRows;
    private FileEntity oldRecord;

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
        this.setIconImage(new ImageIcon("images/logo_1.png").getImage());

        // Load file type items
        for (String item : CommonUtils.TYPE) {
            cb_fileType.addItem(item);
        }
        // Load comment items
        for (String item : CommonUtils.COMMENT) {
            cb_comment.addItem(item);
        }

        editController = new EditController();
        dateFormat = new SimpleDateFormat("dd-MM-yyyy HH.mm.ss aa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mi_edit = new javax.swing.JMenuItem();
        mi_delete = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_facilityNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_vehicleNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cb_fileType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cb_comment = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_returnDetails = new javax.swing.JTable();
        cb_process = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_comment = new javax.swing.JTextArea();
        cb_returnReceived = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_change = new javax.swing.JButton();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);
        jPopupMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPopupMenu1.setPreferredSize(new java.awt.Dimension(160, 60));

        mi_edit.setText("Edit");
        mi_edit.setToolTipText("");
        mi_edit.setAutoscrolls(true);
        mi_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_editActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mi_edit);

        mi_delete.setText("Delete");
        mi_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_deleteActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mi_delete);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Records");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Facility No ");
        jLabel1.setFocusable(false);

        txt_facilityNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_facilityNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_facilityNoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Vehicle No ");
        jLabel2.setFocusable(false);

        txt_vehicleNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("File Type ");
        jLabel3.setFocusable(false);

        cb_fileType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_fileType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--- Select File Type --->" }));
        cb_fileType.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Comment ");
        jLabel4.setFocusable(false);

        cb_comment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_comment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--- Select Comment --->" }));
        cb_comment.setToolTipText("");

        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 200));

        tbl_returnDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_returnDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Return Date", "Process", "Comment", "Return Recived Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_returnDetails.setComponentPopupMenu(jPopupMenu1);
        tbl_returnDetails.setFocusable(false);
        tbl_returnDetails.setRowHeight(20);
        tbl_returnDetails.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_returnDetails.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_returnDetails.setShowGrid(true);
        tbl_returnDetails.getTableHeader().setReorderingAllowed(false);
        tbl_returnDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_returnDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_returnDetails);

        cb_process.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_process.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--- Select Process --->", "Cheque Completed", "Returned to Admin", "Return to Finance", "CEFT Transfered" }));

        txt_comment.setColumns(20);
        txt_comment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_comment.setLineWrap(true);
        txt_comment.setRows(3);
        txt_comment.setTabSize(4);
        jScrollPane3.setViewportView(txt_comment);

        cb_returnReceived.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cb_returnReceived.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--- Select --->", "Yes", "No" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Process ");
        jLabel5.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Comment ");
        jLabel6.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Return Received ");
        jLabel7.setFocusable(false);

        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_remove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        btn_change.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_change.setText("Change");
        btn_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_facilityNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_vehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_fileType, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_returnReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_process, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btn_change, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_fileType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(cb_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_facilityNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txt_vehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_process, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(cb_returnReceived, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_change, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_returnDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_returnDetailsMouseClicked
        DefaultTableModel model = (DefaultTableModel) tbl_returnDetails.getModel();
        if (evt.getClickCount() == 2) {
            cb_process.setSelectedItem(model.getValueAt(tbl_returnDetails.getSelectedRow(), 1));
            txt_comment.setText(model.getValueAt(tbl_returnDetails.getSelectedRow(), 2).toString());

            if (model.getValueAt(tbl_returnDetails.getSelectedRow(), 3).toString().isEmpty()
                    || cb_process.getSelectedIndex() == 1 || cb_process.getSelectedIndex() == 4) {
                cb_returnReceived.setSelectedIndex(2);
            } else {
                cb_returnReceived.setSelectedIndex(1);
            }
        }
    }//GEN-LAST:event_tbl_returnDetailsMouseClicked

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_facilityNo.setEditable(true);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        //
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_facilityNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_facilityNoActionPerformed
        oldRecord = editController.getFileDetails(txt_facilityNo.getText().trim());

        txt_vehicleNo.setText(oldRecord.getVehicleNo());
        cb_fileType.setSelectedIndex(oldRecord.getFileType());
        cb_comment.setSelectedIndex(oldRecord.getComment());

        DefaultTableModel model = (DefaultTableModel) tbl_returnDetails.getModel();
        for (FileReturnHistory record : oldRecord.getReturnHistory()) {
            String returnReceivedDateTime = record.getReceivedDateTime() != null
                    ? dateFormat.format(record.getReceivedDateTime()) : "";
            Object[] obj = {dateFormat.format(record.getReturnedDateTime()), CommonUtils.selectProcess(record.getProcess()),
                record.getUpdatedComment(), returnReceivedDateTime};
            model.addRow(obj);
        }
        
        txt_facilityNo.setEditable(false);
    }//GEN-LAST:event_txt_facilityNoActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        String facilityNo = txt_facilityNo.getText();
        if(!facilityNo.isEmpty()) {
            String reason = JOptionPane.showInputDialog(this, String.format("Do you confirm to remove %s facility from the system?\n "
            + "This operation can not reverse. Please mentione the reason.", facilityNo), "Are you sure?", JOptionPane.WARNING_MESSAGE);
        
            if (reason != null) {
                editController.removeFile(oldRecord, reason, System.getProperty("user.name"));
                JOptionPane.showMessageDialog(this, "Facility removed successfully.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter facility number to remove.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void mi_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_editActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) tbl_returnDetails.getModel();
            cb_process.setSelectedItem(model.getValueAt(tbl_returnDetails.getSelectedRow(), 1));
            txt_comment.setText(model.getValueAt(tbl_returnDetails.getSelectedRow(), 2).toString());
            
            if (model.getValueAt(tbl_returnDetails.getSelectedRow(), 3).toString().isEmpty()
                    || cb_process.getSelectedIndex() == 1 || cb_process.getSelectedIndex() == 4) {
                cb_returnReceived.setSelectedIndex(2);
            } else {
                cb_returnReceived.setSelectedIndex(1);
            }
            
            model.removeRow(tbl_returnDetails.getSelectedRow());
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Please select a row to edit.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mi_editActionPerformed

    private void mi_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_deleteActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Do you wants to remove this entry?", "Remove", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (i == 0) {
//            System.out.println("YES");
            DefaultTableModel model = (DefaultTableModel) tbl_returnDetails.getModel();
            
            //
            
            model.removeRow(tbl_returnDetails.getSelectedRow());
        }
    }//GEN-LAST:event_mi_deleteActionPerformed

    private void btn_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_returnDetails.getModel();
        
        String process = cb_process.getSelectedItem().toString();
        String comment = txt_comment.getText().trim();
        
        if(cb_returnReceived.getSelectedIndex() == 2) {
            model.setValueAt("", model.getRowCount(), 3);
        }
        
        model.addRow(new Object[]{cb_process.getSelectedItem(), txt_comment.getText().trim(), });
        
        cb_process.setSelectedIndex(0);
        cb_returnReceived.setSelectedIndex(0);
        txt_comment.setText("");
    }//GEN-LAST:event_btn_changeActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_change;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_comment;
    private javax.swing.JComboBox<String> cb_fileType;
    private javax.swing.JComboBox<String> cb_process;
    private javax.swing.JComboBox<String> cb_returnReceived;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem mi_delete;
    private javax.swing.JMenuItem mi_edit;
    private javax.swing.JTable tbl_returnDetails;
    private javax.swing.JTextArea txt_comment;
    private javax.swing.JTextField txt_facilityNo;
    private javax.swing.JTextField txt_vehicleNo;
    // End of variables declaration//GEN-END:variables

}
