/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.view;

import com.java.controller.InquiryController;
import javax.swing.ImageIcon;

/**
 *
 * @author 927
 */
public class Inquiry extends javax.swing.JDialog {

  private final InquiryController controller;

  /**
   * Creates new form Inquiry
   *
   * @param facilityNo
   */
  public Inquiry(String facilityNo) {
    initComponents();
    this.setIconImage(new ImageIcon("images/logo_1.png").getImage());
    this.setModalityType(ModalityType.APPLICATION_MODAL);

    controller = new InquiryController(this);
    controller.setData(facilityNo);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_fileType = new javax.swing.JTextField();
        txt_facilityNo = new javax.swing.JTextField();
        txt_vehicleNo = new javax.swing.JTextField();
        txt_acceptedDateTime = new javax.swing.JTextField();
        btn_close = new javax.swing.JButton();
        txt_comment = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_records = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_completedDateTime = new javax.swing.JTextField();
        txt_enteredUser = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payment Inquiry");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payments Inquiry");
        jLabel1.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Facility No.");
        jLabel2.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Vehicle No.");
        jLabel3.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Received Date & Time");
        jLabel4.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("File Type");
        jLabel5.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Comment");
        jLabel6.setFocusable(false);

        txt_fileType.setEditable(false);
        txt_fileType.setBackground(new java.awt.Color(255, 255, 255));
        txt_fileType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_fileType.setFocusable(false);

        txt_facilityNo.setEditable(false);
        txt_facilityNo.setBackground(new java.awt.Color(255, 255, 255));
        txt_facilityNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_facilityNo.setFocusable(false);

        txt_vehicleNo.setEditable(false);
        txt_vehicleNo.setBackground(new java.awt.Color(255, 255, 255));
        txt_vehicleNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_vehicleNo.setFocusable(false);

        txt_acceptedDateTime.setEditable(false);
        txt_acceptedDateTime.setBackground(new java.awt.Color(255, 255, 255));
        txt_acceptedDateTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_acceptedDateTime.setFocusable(false);

        btn_close.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        txt_comment.setEditable(false);
        txt_comment.setBackground(new java.awt.Color(255, 255, 255));
        txt_comment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_comment.setFocusable(false);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(700, 250));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(700, 250));
        jScrollPane2.setViewportView(tbl_records);

        tbl_records.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_records.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ReturnDateTime", "Process", "UpdatedComment", "ReturnReceivedDateTime", "ReturnedUser", "ReturnReceivedUser"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_records.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbl_records.setMaximumSize(new java.awt.Dimension(5000, 150));
        tbl_records.setMinimumSize(new java.awt.Dimension(1000, 150));
        tbl_records.setName("Table Records"); // NOI18N
        tbl_records.setOpaque(false);
        tbl_records.setPreferredSize(new java.awt.Dimension(1200, 150));
        tbl_records.setRowHeight(20);
        tbl_records.setShowGrid(true);
        tbl_records.getTableHeader().setResizingAllowed(false);
        tbl_records.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_records);
        if (tbl_records.getColumnModel().getColumnCount() > 0) {
            tbl_records.getColumnModel().getColumn(0).setResizable(false);
            tbl_records.getColumnModel().getColumn(0).setPreferredWidth(200);
            tbl_records.getColumnModel().getColumn(1).setResizable(false);
            tbl_records.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbl_records.getColumnModel().getColumn(2).setPreferredWidth(300);
            tbl_records.getColumnModel().getColumn(3).setResizable(false);
            tbl_records.getColumnModel().getColumn(3).setPreferredWidth(200);
            tbl_records.getColumnModel().getColumn(4).setResizable(false);
            tbl_records.getColumnModel().getColumn(4).setPreferredWidth(200);
            tbl_records.getColumnModel().getColumn(5).setResizable(false);
            tbl_records.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Complete Date & Time");
        jLabel7.setFocusable(false);

        txt_completedDateTime.setEditable(false);
        txt_completedDateTime.setBackground(new java.awt.Color(255, 255, 255));
        txt_completedDateTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_completedDateTime.setFocusable(false);

        txt_enteredUser.setEditable(false);
        txt_enteredUser.setBackground(new java.awt.Color(255, 255, 255));
        txt_enteredUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_enteredUser.setFocusable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Entered User");
        jLabel8.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_enteredUser, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_completedDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel6))
                                            .addGap(20, 20, 20)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txt_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txt_vehicleNo)
                                                        .addComponent(txt_facilityNo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(27, 27, 27)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel4)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(txt_acceptedDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel5)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(txt_fileType, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                                .addGap(29, 29, 29)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_facilityNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_acceptedDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_vehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_fileType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_completedDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txt_enteredUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 54, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
    this.dispose();
  }//GEN-LAST:event_btn_closeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tbl_records;
    public javax.swing.JTextField txt_acceptedDateTime;
    public javax.swing.JTextField txt_comment;
    public javax.swing.JTextField txt_completedDateTime;
    public javax.swing.JTextField txt_enteredUser;
    public javax.swing.JTextField txt_facilityNo;
    public javax.swing.JTextField txt_fileType;
    public javax.swing.JTextField txt_vehicleNo;
    // End of variables declaration//GEN-END:variables

}
