/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.view;

import com.java.CommonUtils;
import com.java.controller.URVehicleNoUpdateController;
import com.java.entity.FileEntity;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Madushan Lahiru
 */
public class URVehicleNoUpdate extends javax.swing.JFrame {

  List<FileEntity> files;
  private final URVehicleNoUpdateController controller;

  /**
   * Creates new form URVehicleNoUpdate
   */
  public URVehicleNoUpdate() {
    initComponents();
    this.setIconImage(new ImageIcon("images/logo_1.png").getImage());

    controller = new URVehicleNoUpdateController(this);
    try {
      controller.loadAllData();
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(URVehicleNoUpdate.class.getName()).log(Level.SEVERE, null, ex);
    }

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_facilityNoSearch = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_clearSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_URVehicles = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_facilityNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_vehicleNo = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("U/R Vehicle No Update");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Facility No");
        jLabel3.setFocusable(false);

        txt_facilityNoSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_facilityNoSearch.setNextFocusableComponent(btn_search);
        txt_facilityNoSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_facilityNoSearchActionPerformed(evt);
            }
        });

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_search.setText("Search");
        btn_search.setNextFocusableComponent(txt_facilityNo);
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_clearSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_clearSearch.setText("Clear");
        btn_clearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_facilityNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_facilityNoSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_clearSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbl_URVehicles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_URVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Facility No", "Vehicle No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_URVehicles.setRowHeight(20);
        tbl_URVehicles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_URVehicles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_URVehicles.setShowGrid(true);
        tbl_URVehicles.getTableHeader().setReorderingAllowed(false);
        tbl_URVehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_URVehiclesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_URVehicles);
        if (tbl_URVehicles.getColumnModel().getColumnCount() > 0) {
            tbl_URVehicles.getColumnModel().getColumn(0).setResizable(false);
            tbl_URVehicles.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehicle No Update", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Facility No");
        jLabel1.setFocusable(false);

        txt_facilityNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_facilityNo.setNextFocusableComponent(txt_vehicleNo);
        txt_facilityNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_facilityNoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Vehicle No");
        jLabel2.setFocusable(false);

        txt_vehicleNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_vehicleNo.setNextFocusableComponent(btn_update);
        txt_vehicleNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_vehicleNoFocusGained(evt);
            }
        });

        btn_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_facilityNo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_vehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_facilityNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_vehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void tbl_URVehiclesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_URVehiclesMouseClicked
    if (evt.getClickCount() == 2) {
      txt_facilityNo.setEditable(false);
      txt_facilityNo.setText(tbl_URVehicles.getValueAt(tbl_URVehicles.getSelectedRow(), 0).toString());
      txt_vehicleNo.setText(tbl_URVehicles.getValueAt(tbl_URVehicles.getSelectedRow(), 1).toString());
      txt_facilityNo.nextFocus();
    }
  }//GEN-LAST:event_tbl_URVehiclesMouseClicked

  private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
    controller.clear();
    tbl_URVehicles.clearSelection();
  }//GEN-LAST:event_btn_clearActionPerformed

  private void txt_facilityNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_facilityNoActionPerformed
    if (CommonUtils.facilityNoValidator(txt_facilityNo.getText().trim().toUpperCase())) {
      String facNo = null, VehiNo = null;
      for (FileEntity file : files) {
        if (file.getFacilityNo().equals(txt_facilityNo.getText().trim().toUpperCase())) {
          facNo = file.getFacilityNo();
          VehiNo = file.getVehicleNo();
        }
      }
      if (facNo != null) {
        txt_vehicleNo.setText(VehiNo);
        txt_facilityNo.nextFocus();
      } else {
        JOptionPane.showMessageDialog(this, "Please enter valid facility number.", "Not Found", JOptionPane.WARNING_MESSAGE);
      }
    } else {
      JOptionPane.showMessageDialog(this, "Please enter valid facility number.", "Warning", JOptionPane.WARNING_MESSAGE);
    }
  }//GEN-LAST:event_txt_facilityNoActionPerformed

  private void txt_vehicleNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_vehicleNoFocusGained
    txt_vehicleNo.selectAll();
  }//GEN-LAST:event_txt_vehicleNoFocusGained

  private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
    if (CommonUtils.vehicleNoValidator(txt_vehicleNo.getText().trim().toUpperCase())) {
      int success = 0;
      try {
        success = controller.update(txt_facilityNo.getText().trim().toUpperCase(), txt_vehicleNo.getText().trim().toUpperCase());
      } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database connection not found.", "Error", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(URVehicleNoUpdate.class.getName()).log(Level.SEVERE, null, ex);
      }
      if (success == 1) {
        JOptionPane.showMessageDialog(this, "Data saved successfuly.", "Success", JOptionPane.INFORMATION_MESSAGE);
        btn_clearActionPerformed(null);
        try {
          controller.loadAllData();
        } catch (ClassNotFoundException | SQLException ex) {
          Logger.getLogger(URVehicleNoUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
      } else {
        JOptionPane.showMessageDialog(this, "Error on data save, Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
      }
    } else {
      JOptionPane.showMessageDialog(this, "Please enter valid vehicle number.", "Warning", JOptionPane.WARNING_MESSAGE);
    }
  }//GEN-LAST:event_btn_updateActionPerformed

  private void txt_facilityNoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_facilityNoSearchActionPerformed
    btn_searchActionPerformed(new ActionEvent(this, 0, null));
  }//GEN-LAST:event_txt_facilityNoSearchActionPerformed

  private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
    try {
      controller.search(txt_facilityNoSearch.getText().trim().toUpperCase());
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(URVehicleNoUpdate.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
      Logger.getLogger(URVehicleNoUpdate.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btn_searchActionPerformed

  private void btn_clearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearSearchActionPerformed
    txt_facilityNoSearch.setText("");
    try {
      controller.loadAllData();
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(URVehicleNoUpdate.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btn_clearSearchActionPerformed

  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    try {
      controller.close();
      
      Dashboard dashboard = new Dashboard();
      dashboard.setVisible(true);
    } catch (SQLException ex) {
      Logger.getLogger(URVehicleNoUpdate.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_clearSearch;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tbl_URVehicles;
    public javax.swing.JTextField txt_facilityNo;
    public javax.swing.JTextField txt_facilityNoSearch;
    public javax.swing.JTextField txt_vehicleNo;
    // End of variables declaration//GEN-END:variables

}
